name: simple_crud_with_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  get_cli: ^1.8.1
  get: 4.6.5
  dio: ^5.1.1
  shared_preferences: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

